services:
  - type: web
    name: nasdaq-screener-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
